-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 20:55:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cas100
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cas100
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cas100` DEFAULT CHARACTER SET utf8 ;
USE `cas100` ;

-- -----------------------------------------------------
-- Table `cas100`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`user` ;

CREATE TABLE IF NOT EXISTS `cas100`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `email` VARCHAR(45) NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45)  NULL,
  `grad_year` INT(4) NULL,
  `admin` TINYINT  NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cas100`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`product` ;

CREATE TABLE IF NOT EXISTS `cas100`.`product` (
  `idproduct` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` INT NOT NULL,
  `image_url` VARCHAR(45) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cas100`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`cart` ;

CREATE TABLE IF NOT EXISTS `cas100`.`cart` (
  `idcart` INT NOT NULL,
  `iduser` INT NOT NULL,
  `ordered` TINYINT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `iduser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `cas100`.`user` (`iduser`)
    ON DELETE CASCADE
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cas100`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `cas100`.`cart_item` (
  `idcart_item` INT NOT NULL,
  `idcart` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idcart_item`),
  INDEX `idcart_idx` (`idcart` ASC) VISIBLE,
  INDEX `idproduct_idx` (`idproduct` ASC) VISIBLE,
  CONSTRAINT `idcart`
    FOREIGN KEY (`idcart`)
    REFERENCES `cas100`.`cart` (`idcart`)
    ON DELETE CASCADE,
  CONSTRAINT `idproduct`
    FOREIGN KEY (`idproduct`)
    REFERENCES `cas100`.`product` (`idproduct`)
    ON DELETE CASCADE
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cas100`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`event` ;

CREATE TABLE IF NOT EXISTS `cas100`.`event` (
  `idevent` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `description` VARCHAR(255) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idevent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cas100`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cas100`.`registration` ;

CREATE TABLE IF NOT EXISTS `cas100`.`registration` (
  `idregistration` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idevent` INT NOT NULL,
  PRIMARY KEY (`idregistration`),
  INDEX `iduser_idx` (`iduser` ASC) VISIBLE,
  INDEX `idevent_idx` (`idevent` ASC) VISIBLE,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `cas100`.`user` (`iduser`)
    ON DELETE CASCADE,
  CONSTRAINT `idevent`
    FOREIGN KEY (`idevent`)
    REFERENCES `cas100`.`event` (`idevent`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
